# Generated by Django 5.0.4 on 2024-04-06 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExercisesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('video', models.ImageField(blank=True, upload_to='exercises_info_video/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
