name: Update Requirements Changes

on:
  push:
    paths:
      - 'docs/requirements/**'

jobs:
  echo_message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Get changed files from API
        id: changed-files
        uses: actions/github-script@v5
        with:
          script: |
            const payload = context.payload;
            const before = payload.before;
            const after = payload.after;
            const response = await github.rest.repos.compareCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: before,
              head: after
            });
            const files = response.data.files.map(file => file.filename).join("\n");
            console.log(files); // 콘솔에 변경된 파일 목록을 출력합니다.
            core.setOutput("list", files);  # 변경된 파일 목록을 출력 변수로 설정합니다.

      - name: Save changed files
        id: save-changed-files
        run: |
          echo "${{ steps.changed-files.outputs.list }}"
          echo "${{ steps.changed-files.outputs.list }}" > changed_files.txt
        shell: bash

      - name: Update requirements changes
        id: update-requirements
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          python3 update_requirements.py changed_files.txt ${PAT}