name: Update Requirements Changes

on:
  push:
    paths:
      - 'docs/requirements/**'

jobs:
  process-changed-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get changed files
        uses: actions/github-script@v5
        id: changed-files
        with:
          script: |
            const payload = context.payload;
            const before = payload.before;
            const after = payload.after;
            const response = await github.rest.repos.compareCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: before,
              head: after
            });
            const files = response.data.files.map(file => file.filename).join("\n");
            console.log(files); // 콘솔에 변경된 파일 목록을 출력합니다.
            core.setOutput("list", files); // 변경된 파일 목록을 출력 변수로 설정

      - name: Process each changed file
        run: |
          IFS=$'\n' read -r -d '' -a files <<< "${{ steps.changed-files.outputs.list }}"
          for file in "${files[@]}"; do
            if [[ $file == docs/requirements/*_requirements.md ]]; then
              echo "Processing $file"
              python3 utils/update_requirements.py "$file" ${{ secrets.PAT }}
            fi
          done
        shell: bash
