name: Update Requirements

on:
  push:
    paths:
      - '**requirements.md'

jobs:
  UpdateRequirements:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.0'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: get_changed_files
        id: get_changed_files
        run: |
          python3 get_changed_files.py